.TH "hackrf_rffc5071" 1 "2013.07.1" HACKRF "User Commands"
.SH NAME
hackrf_rffc5071 \- chip register read/write tool
.SH DESCRIPTION
The HackRF project started by Michael Ossmann and Jared Boone to build
software radio peripheral using Free Software and Free Hardware
design. Care was taken to only use electronic components with
published documentation (no NDAs!) and to avoid software libraries
without open source licenses.
.LP
Jawbreaker is the first complete HackRF platform, a wideband software radio
transceiver with a USB interface.
.LP
This application lets the user control the rffc5071 chip.
.SH SYNOPSIS
.B  hackrf_rffc5071 [OPTIONS]
.SH OPTIONS
.IP "-n, --register <n>: set register number for subsequent read/write operations"
.IP "-r, --read: read register specified by last -n argument, or all registers"
.IP "-w, --write <v>: write register specified by last -n argument with value <v>"
.SH EXAMPLES
.IP "hackrf_rffc5071 -n 12 -r # reads from register 12"
.IP "hackrf_rffc5071 -r # reads all registers"
.IP "hackrf_rffc5071 -n 10 -w 514 # writes register 10 with 514 decimal"
.SH SEE ALSO
Great Scott Gadgets HackRF web page:
.B http://greatscottgadgets.com/hackrf/
.LP
Other hackrf programs:
.sp
hackrf_cpldjtag(1), hackrf_info(1), hackrf_max2837(1), hackrf_si5351c(1), hackrf_spiflash(1), hackrf_transfer(1)
.SH AUTHOR
This manual page was written by Maitland Bottoms
for the Debian project (but may be used by others).
.SH COPYRIGHT
Copyright (c) 2013 A. Maitland Bottoms <bottoms@debian.org>
.LP
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
(at your option) any later version.
.LP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
