.TH "airspy_spiflash" 1 "2014.04.18" AIRSPY "User Commands"
.SH NAME
airspy_spiflash \- program Flash
.SH DESCRIPTION
The Airspy is a tiny and efficient software defined radio receiver.
.LP
This application lets the user configure the on-board Flash.
.SH SYNOPSIS
.B  airspy_spiflash [OPTIONS]
.SH OPTIONS
.IP "-a, --address <n>: starting address (default: 0)"
.IP "-l, --length <n>: number of bytes to read (default: 0)"
.IP "-r <filename>: Read data into file (SPIFI@0x80000000)."
.IP "-w <filename>: Write data from file."
.SH SEE ALSO
Airspy web page:
.B http://airspy.com/
.LP
Other airspy programs:
.sp
airspy_info(1), airspy_rx(1), airspy_si5351c(1), airspy_r820t(1)
.SH AUTHOR
This manual page was written by Maitland Bottoms
for the Debian project (but may be used by others).
.SH COPYRIGHT
Copyright (c) 2014 A. Maitland Bottoms <bottoms@debian.org>
.LP
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
(at your option) any later version.
.LP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
