.TH "airspy_rx" 1 "2014.04.18" AIRSPY "User Commands"
.SH NAME
airspy_rx \- probe device and show configuration
.SH DESCRIPTION
The Airspy is a tiny and efficient software defined radio receiver.
.LP
This application lets the user probe the device and show configuration.
.SH SYNOPSIS
.B  airspy_rx
.SH OPTIONS
.IP "-r <filename> # Receive data into file."
.IP "-w # Receive data into file with WAV header and automatic name."
.IP "# This is for SDR# compatibility and may not work with other software."
.IP "[-f set_freq_hz] # Set Freq in Hz between [24MHz, 1750MHz]."
.IP "[-v gain] # Set VGA gain, 0-15 (default 0)"
.IP "[-m gain] # Set Mixer gain, 0-15 (default 8)"
.IP "[-l gain] # Set LNA gain, 0-14 (default 8)"
.IP "[-n num_samples] # Number of samples to transfer (default is unlimited)."
.SH SEE ALSO
Airspy web page:
.B http://airspy.com/
.LP
Other airspy programs:
.sp
airspy_info(1), airspy_si5351c(1), airspy_spiflash(1)
.SH AUTHOR
This manual page was written by Maitland Bottoms
for the Debian project (but may be used by others).
.SH COPYRIGHT
Copyright (c) 2014 A. Maitland Bottoms <bottoms@debian.org>
.LP
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
(at your option) any later version.
.LP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
